name = "flash"
version = "0.1.0"
license = "license"
author = "jscilipoti"
maintainer = "jscilipoti@gmail.com"
copyright = "Copyright 2023, jscilipoti"
fortran.implicit-typing = true
fortran.implicit-external = true
fortran.source-form = "free"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[dependencies]
stdlib="*"

